version: '3'

tasks:
  setup:
    desc: Setup development environment
    cmds:
      - uv venv .venv
      - uv pip install -e .
      - uv pip install pytest mypy ruff pytest-cov

  install:
    desc: Install dependencies using uv
    cmds:
      - uv pip install -e .

  run:
    desc: Run the file manager
    cmds:
      - .venv/bin/python -m better_file_manager.main

  test:
    desc: Run tests with pytest
    cmds:
      - .venv/bin/python -m pytest tests/ --cov=better_file_manager

  lint:
    desc: Run ruff linter
    cmds:
      - .venv/bin/python -m ruff check .

  typecheck:
    desc: Run mypy type checker
    cmds:
      - .venv/bin/python -m mypy better_file_manager

  check:
    desc: Run all checks (lint, typecheck, test)
    cmds:
      - task: lint
      - task: typecheck
      - task: test

  clean:
    desc: Clean build artifacts and cache
    cmds:
      - rm -rf build/ dist/ *.egg-info .pytest_cache .coverage .mypy_cache .ruff_cache
      - find . -type d -name "__pycache__" -exec rm -rf {} +

  clean-venv:
    desc: Remove virtual environment
    cmds:
      - rm -rf .venv
