version: '3'

tasks:
  setup:
    desc: Setup development environment
    cmds:
      - python -m venv .venv
      - source .venv/bin/activate && python -m pip install uv
      - source .venv/bin/activate && uv pip install -e .
      - source .venv/bin/activate && uv pip install pytest mypy ruff pytest-cov

  install:
    desc: Install dependencies using uv
    cmds:
      - source .venv/bin/activate && uv pip install -e .

  run:
    desc: Run the file manager
    cmds:
      - source .venv/bin/activate && python -m better_file_manager.main

  test:
    desc: Run tests with pytest
    cmds:
      - source .venv/bin/activate && pytest tests/ --cov=better_file_manager

  lint:
    desc: Run ruff linter
    cmds:
      - source .venv/bin/activate && ruff check .

  typecheck:
    desc: Run mypy type checker
    cmds:
      - source .venv/bin/activate && mypy better_file_manager

  check:
    desc: Run all checks (lint, typecheck, test)
    cmds:
      - task: lint
      - task: typecheck
      - task: test

  clean:
    desc: Clean build artifacts and cache
    cmds:
      - rm -rf build/ dist/ *.egg-info .pytest_cache .coverage .mypy_cache .ruff_cache
      - find . -type d -name "__pycache__" -exec rm -rf {} +
